Harden test helper to recover from poisoned mutex
Before, when a test panics the mutex is poisoned:

```
thread 'path_facts::tests::test_rename_two_missing_paths' (2428) panicked at src/test_help.rs:14:44:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

That poison tells us that the contents might not be what we expect. Instead of holding onto the original CWD of each call, we can hold onto the very first CWD and use that in our drop statement.