Fix windows
```
Annotations
1 error
test (windows-2022)
failed 7 minutes ago in 42s
Search logs
2s
5s
18s
6s
3s
3s
Run bin/test
    Updating crates.io index
   Compiling path_facts v0.2.2 (D:\a\path_facts\path_facts)
warning: unused import: `happy_path::DirOk`
 --> src\fact_check.rs:6:67
  |
6 |     use crate::{abs_path::AbsPath, canonical_path::CanonicalPath, happy_path::DirOk};
  |                                                                   ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` (part of `#[warn(unused)]`) on by default

warning: unused import: `crate::abs_path::AbsPath`
   --> src\path_facts.rs:312:9
    |
312 |     use crate::abs_path::AbsPath;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0026]: variant `trace::PhysicalNode::ParentDir` does not have a field named `to`
    --> src\trace.rs:1224:39
     |
1224 |             PhysicalNode::ParentDir { to, .. } => assert_eq!(
     |                                       ^^ variant `trace::PhysicalNode::ParentDir` does not have this field

For more information about this error, try `rustc --explain E0026`.
warning: `path_facts` (lib test) generated 2 warnings
error: could not compile `path_facts` (lib test) due to 1 previous error; 2 warnings emitted
warning: build failed, waiting for other jobs to finish...
error: command `'C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe' test --no-run --message-format json-render-diagnostics` exited with code 101
```